spring:
  profiles: default
  application:
    name: Eureka
server:
  port: 5555
eureka:
  instance:
    hostname: Eureka-instance-default.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
---
spring:
  profiles: EurekaClusterInstance-1
  application:
    name: Eureka
server:
  port: 5556
eureka:
  instance:
    hostname: Eureka-Cluster-instance1.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://Eureka-Cluster-instance2.com:5557/eureka/,http://Eureka-Cluster-instance3.com:5558/eureka/
---
spring:
  profiles: EurekaClusterInstance-2
  application:
    name: Eureka
server:
  port: 5557
eureka:
  instance:
    hostname: Eureka-Cluster-instance2.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://Eureka-Cluster-instance1.com:5556/eureka/,http://Eureka-Cluster-instance3.com:5558/eureka/
---
spring:
  profiles: EurekaClusterInstance-3
  application:
    name: Eureka
server:
  port: 5558
eureka:
  instance:
    hostname: Eureka-Cluster-instance3.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://Eureka-Cluster-instance2.com:5557/eureka/,http://Eureka-Cluster-instance1.com:5556/eureka/
